#!/bin/sh

# ON or OFF WPS-led

if [ $1 == 0 ]
then
echo 0 > /sys/devices/platform/leds-gpio/leds/tp-link\:green\:wps/brightness
fi

if [ $1 == 1 ]
then
echo 1 > /sys/devices/platform/leds-gpio/leds/tp-link\:green\:wps/brightness
fi
