#!/bin/sh
logger The $BUTTON was action $ACTION

if [[ $BUTTON == 'BTN_0' && $ACTION == 'pressed' ]]
then
uci set wifi.ruleup.btn_0=1
fi
if [[ $BUTTON == 'BTN_0' && $ACTION == 'released' ]]
then
uci set wifi.ruleup.btn_0=0
fi
if [[ $BUTTON == 'BTN_1' && $ACTION == 'pressed' ]]
then
uci set wifi.ruleup.btn_1=1
fi
if [[ $BUTTON == 'BTN_1' && $ACTION == 'released' ]]
then
uci set wifi.ruleup.btn_1=0
fi
uci commit wifi

A=$(uci get wifi.ruleup.btn_0)
B=$(uci get wifi.ruleup.btn_1)

if [[ $A == 0 && $B == 1 ]]
then
uci set wifi.ruleup.mode=WISP
fi
if [[ $A == 1 && $B == 1 ]]
then
uci set wifi.ruleup.mode=AP
fi
if [[ $A == 1 && $B == 0 ]]
then
uci set wifi.ruleup.mode=3G
fi
uci commit wifi
